"""
PVT Studio — ECLIPSE 300 (compositional) PROPS export.

Writes the Peng-Robinson fluid characterization used by the app as an
E300 include file, so the SAME EOS (including a tuned C7+ and tuned
binary interaction coefficients) runs in the compositional simulator:

    CNAMES, EOS PR + PRCORR, TCRIT, PCRIT, VCRIT, ZCRIT, ACF, MW,
    PARACHOR, BIC (lower triangle), RTEMP, STCOND, ZI

Units follow the deck unit set:
    FIELD : TCRIT degR, PCRIT psia, VCRIT ft3/lb-mole, RTEMP degF
    METRIC: TCRIT K,    PCRIT bara, VCRIT m3/kg-mole,  RTEMP degC

RUNSPEC must contain the matching unit keyword and  COMPS  <n> /.
The app's PR uses the 1978 m(omega) for omega > 0.49, hence PRCORR.
No volume shift is used (no SSHIFT); LBC viscosity uses VCRIT with the
standard LBC coefficients (E300 defaults), which match the app.
"""

APP_VERSION = "1.4.2"   # must match pvt_app.py (deployment check)

import datetime as _dt
import numpy as np

from components import get_props, kij as _kij

R_FIELD = 10.7316                      # psia ft3 / (lbmol degR)
FT3_PER_LBMOL_TO_M3_PER_KMOL = 0.0283168 / 0.453592   # = 0.062428


def _name8(n):
    """E300 component names are at most 8 characters."""
    return str(n)[:8]


def e300_component_table(comp_names, c7_props=None, kij_overrides=None):
    """Per-component properties (FIELD units) + the BIC matrix."""
    rows = []
    for c in comp_names:
        p = get_props(c, c7_props)
        Tc, Pc, Vc = float(p["Tc"]), float(p["Pc"]), float(p["Vc"])
        rows.append({"name": c, "Tc_R": Tc, "Pc_psia": Pc,
                     "Vc_ft3": Vc, "Zc": Pc * Vc / (R_FIELD * Tc),
                     "omega": float(p["omega"]), "MW": float(p["MW"]),
                     "parachor": float(p.get("P_ch", 0.0))})
    n = len(comp_names)
    K = np.zeros((n, n))
    ov = {}
    for (a, b), v in (kij_overrides or {}).items():
        ov[(a, b)] = ov[(b, a)] = float(v)
    for i in range(n):
        for j in range(n):
            if i != j:
                K[i, j] = ov.get((comp_names[i], comp_names[j]),
                                 _kij(comp_names[i], comp_names[j]))
    return rows, K


def build_e300_props(comp_names, z, T_res_F, c7_props=None, units="METRIC",
                     kij_overrides=None, psat_psia=None, sat_kind=None,
                     title="PVT Studio compositional fluid"):
    """Return the E300 PROPS include file as text."""
    units = "METRIC" if str(units).upper() == "METRIC" else "FIELD"
    z = np.asarray(z, dtype=float)
    z = z / z.sum()
    rows, K = e300_component_table(comp_names, c7_props, kij_overrides)
    n = len(rows)
    metric = units == "METRIC"

    def col(key, fmt, conv=lambda v: v):
        return ["   " + fmt % conv(r[key]) for r in rows] + ["/"]

    T_unit, P_unit, V_unit = (("K", "bara", "m3/kg-mole") if metric
                              else ("degR", "psia", "ft3/lb-mole"))
    now = _dt.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    L = [
        "-- " + "=" * 66,
        f"-- {title}",
        f"-- ECLIPSE 300 compositional PROPS — generated by PVT Studio {now}",
        f"-- Units: {units}.  RUNSPEC must contain:  {units}  and  "
        f"COMPS  {n} /",
        "-- Peng-Robinson EOS (1978 m(omega) for omega > 0.49 -> PRCORR),",
        "-- no volume shift, LBC viscosity from VCRIT (E300 default coeffs).",
    ]
    if psat_psia:
        ps = psat_psia / 14.50377 if metric else psat_psia
        L.append(f"-- {sat_kind or 'Saturation'} pressure at RTEMP from the "
                 f"app's EOS: {ps:.2f} {'bara' if metric else 'psia'} "
                 f"(QC target for the E300 run)")
    L += ["-- " + "=" * 66, "",
          "CNAMES"] + ["   " + _name8(r["name"]) for r in rows] + ["/", "",
          "EOS", "   PR /", "", "PRCORR", ""]
    L += [f"-- Critical temperature ({T_unit})", "TCRIT"]
    L += col("Tc_R", "%12.4f", (lambda v: v / 1.8) if metric else (lambda v: v))
    L += ["", f"-- Critical pressure ({P_unit})", "PCRIT"]
    L += col("Pc_psia", "%12.4f", (lambda v: v / 14.50377) if metric else (lambda v: v))
    L += ["", f"-- Critical volume ({V_unit})", "VCRIT"]
    L += col("Vc_ft3", "%12.6f",
             (lambda v: v * FT3_PER_LBMOL_TO_M3_PER_KMOL) if metric
             else (lambda v: v))
    L += ["", "-- Critical Z-factor", "ZCRIT"] + col("Zc", "%12.6f")
    L += ["", "-- Acentric factor", "ACF"] + col("omega", "%12.6f")
    L += ["", "-- Molecular weight", "MW"] + col("MW", "%12.4f")
    L += ["", "-- Parachors", "PARACHOR"] + col("parachor", "%12.4f")
    L += ["", "-- Binary interaction coefficients (lower triangle, by row)",
          "BIC"]
    for i in range(1, n):
        L.append("   " + " ".join("%8.5f" % K[i, j] for j in range(i))
                 + f"   -- {_name8(rows[i]['name'])}")
    L += ["/", "",
          f"-- Reservoir temperature ({'degC' if metric else 'degF'})",
          "RTEMP",
          "   %.3f /" % (((T_res_F - 32.0) / 1.8) if metric else T_res_F), "",
          "-- Standard conditions (temperature, pressure)",
          "STCOND",
          ("   15.556  1.01325 /" if metric else "   60.0  14.696 /"), "",
          "-- Initial (reservoir fluid) composition, mole fraction",
          "ZI"]
    L += ["   %.6f   -- %s" % (zi, _name8(r["name"])) for zi, r in zip(z, rows)]
    L += ["/", ""]
    from units import to_ascii
    return to_ascii("\n".join(L))


def parse_e300_props(text):
    """Minimal reader used by the QC: keyword -> list of numbers/strings."""
    out, cur = {}, None
    for line in text.splitlines():
        s = line.split("--")[0].strip()
        if not s:
            continue
        if cur is None:
            if s.replace("_", "").isalpha() and s.isupper():
                cur = s
                out[cur] = []
                if cur in ("PRCORR",):
                    cur = None
            continue
        if s == "/":
            cur = None
            continue
        toks = s.rstrip("/").split()
        out[cur].extend(toks)
        if s.endswith("/"):
            cur = None
    return out


def qc_e300_props(text, n):
    """Structural QC: every per-component keyword has n entries, BIC has
    n(n-1)/2, ZI sums to 1, all criticals positive."""
    kw = parse_e300_props(text)
    errs = []
    for key in ("CNAMES", "TCRIT", "PCRIT", "VCRIT", "ZCRIT", "ACF", "MW",
                "PARACHOR", "ZI"):
        got = len(kw.get(key, []))
        if got != n:
            errs.append(f"{key}: {got} entries, expected {n}.")
    nb = len(kw.get("BIC", []))
    if nb != n * (n - 1) // 2:
        errs.append(f"BIC: {nb} entries, expected {n * (n - 1) // 2}.")
    try:
        if abs(sum(float(v) for v in kw.get("ZI", [])) - 1.0) > 1e-4:
            errs.append("ZI does not sum to 1.")
        for key in ("TCRIT", "PCRIT", "VCRIT", "MW"):
            if any(float(v) <= 0 for v in kw.get(key, [])):
                errs.append(f"{key}: non-positive value.")
        zc = [float(v) for v in kw.get("ZCRIT", [])]
        if zc and not all(0.1 < v < 0.5 for v in zc):
            errs.append("ZCRIT outside 0.1–0.5 — check critical volumes.")
    except ValueError:
        errs.append("Non-numeric value in a numeric keyword.")
    for key in ("EOS", "RTEMP", "STCOND"):
        if key not in kw:
            errs.append(f"{key} keyword missing.")
    return {"ok": not errs, "problems": errs}


def build_gem_eos(comp_names, z, T_res_F, c7_props=None, units="METRIC",
                  kij_overrides=None, title="PVT Studio compositional fluid"):
    """CMG GEM component-property block for the same PR fluid.

    GEM reads the component criticals in fixed units whatever *INUNIT is:
    PCRIT atm, TCRIT K, VCRIT m3/kmol (= l/gmol). *TRES follows *INUNIT
    (degC for *SI, degF for *FIELD). *ZGLOBALC belongs in the
    initial-conditions section and is written as a commented block.
    """
    units = "METRIC" if str(units).upper() == "METRIC" else "FIELD"
    z = np.asarray(z, dtype=float)
    z = z / z.sum()
    rows, K = e300_component_table(comp_names, c7_props, kij_overrides)
    n = len(rows)

    def line(vals, fmt):
        return "   " + " ".join(fmt % v for v in vals)

    now = _dt.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    L = ["** " + "=" * 66,
         f"** {title}",
         f"** CMG GEM component properties - generated by PVT Studio {now}",
         "** Peng-Robinson (1978 m(omega) correction: *PRCORR 1), no volume",
         "** shift. Criticals in GEM's fixed units: atm, K, m3/kmol.",
         "** " + "=" * 66, "",
         "*MODEL *PR",
         f"*NC {n} {n}",
         "*PRCORR 1",
         "*COMPNAME " + " ".join("'%s'" % _name8(r["name"]) for r in rows),
         "*TCRIT", line([r["Tc_R"] / 1.8 for r in rows], "%.4f"),
         "*PCRIT", line([r["Pc_psia"] / 14.69595 for r in rows], "%.4f"),
         "*VCRIT", line([r["Vc_ft3"] * FT3_PER_LBMOL_TO_M3_PER_KMOL
                         for r in rows], "%.6f"),
         "*AC", line([r["omega"] for r in rows], "%.6f"),
         "*MW", line([r["MW"] for r in rows], "%.4f"),
         "*PCHOR", line([r["parachor"] for r in rows], "%.4f"),
         "*BIN"]
    for i in range(1, n):
        L.append("   " + " ".join("%.5f" % K[i, j] for j in range(i))
                 + f"   ** {_name8(rows[i]['name'])}")
    L += ["",
          f"*TRES {((T_res_F - 32.0) / 1.8) if units == 'METRIC' else T_res_F:.3f}"
          f"   ** {'degC (*INUNIT *SI)' if units == 'METRIC' else 'degF (*INUNIT *FIELD)'}",
          "",
          "** Initial composition - paste into the initial-conditions section:",
          "** *ZGLOBALC " + " ".join("%.6f" % v for v in z), ""]
    from units import to_ascii
    return to_ascii("\n".join(L))
