"""
Export utilities for PVT Studio.

  - CSV  : pandas-based, any DataFrame
  - JSON : structured payload for API consumption
  - PDF  : compact report summarizing inputs and outputs
            Uses reportlab; imported lazily so missing dep doesn't break the app.
"""

import io
import json
from datetime import datetime


def df_to_csv_bytes(df):
    """DataFrame to CSV bytes for st.download_button."""
    buf = io.StringIO()
    df.to_csv(buf, index=False)
    return buf.getvalue().encode("utf-8")


def to_json_bytes(payload, indent=2):
    """Dict/list -> JSON bytes."""
    return json.dumps(payload, indent=indent, default=_json_default).encode("utf-8")


def _json_default(o):
    try:
        import numpy as np
        if isinstance(o, np.ndarray): return o.tolist()
        if isinstance(o, np.integer): return int(o)
        if isinstance(o, np.floating): return float(o)
    except ImportError:
        pass
    return str(o)


def build_api_payload(fluid_type, units, inputs, outputs, metadata=None):
    """
    Structured payload for downstream API consumption.

    Example output:
    {
        "metadata": {"timestamp": "...", "tool": "PVT Studio v1.0"},
        "fluid_type": "oil",
        "units": "Field",
        "inputs":   {"api": 35, "gas_sg": 0.75, ...},
        "outputs":  {"Pb": 2570, "table": [{"P": ..., "Bo": ..., ...}, ...]}
    }
    """
    return {
        "metadata": {
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "tool": "PVT Studio v1.0",
            "author": "Merouane Hamdani",
            **(metadata or {}),
        },
        "fluid_type": fluid_type,
        "units": units,
        "inputs": inputs,
        "outputs": outputs,
    }


# ---------------------------------------------------------------
# PDF report (lazy import — only loaded if user requests PDF)
# ---------------------------------------------------------------
def build_pdf_report(title, fluid_type, units, inputs, outputs_text,
                      tables=None, notes=""):
    """
    Build a PDF report summarizing the analysis.

    Args:
        title         : Page title
        fluid_type    : e.g. "Oil (Black Oil)"
        units         : "Field" or "SI"
        inputs        : dict of input parameters
        outputs_text  : list of summary strings to include
        tables        : list of (title, pandas DataFrame) pairs
        notes         : closing notes

    Returns PDF as bytes, or None if reportlab is not installed.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.colors import HexColor, black, white, grey
        from reportlab.lib.units import cm, mm
        from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                         Table, TableStyle, PageBreak)
    except ImportError:
        return None

    EQUINOR_RED = HexColor("#EB0037")
    DARK_NAVY = HexColor("#00243D")

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                             leftMargin=2*cm, rightMargin=2*cm,
                             topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "TitleStyle", parent=styles["Title"], textColor=DARK_NAVY,
        fontSize=18, spaceAfter=14)
    section_style = ParagraphStyle(
        "Section", parent=styles["Heading2"], textColor=EQUINOR_RED,
        fontSize=13, spaceBefore=10, spaceAfter=6)
    body_style = ParagraphStyle(
        "Body", parent=styles["BodyText"], fontSize=10, spaceAfter=4)

    story = []
    # Header
    story.append(Paragraph(f"<b>{title}</b>", title_style))
    story.append(Paragraph(
        f"<i>Generated by PVT Studio v1.0 (M. Hamdani) on "
        f"{datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</i>",
        body_style))
    story.append(Spacer(1, 6*mm))

    # Metadata
    story.append(Paragraph("Analysis Summary", section_style))
    story.append(Paragraph(f"<b>Fluid type:</b> {fluid_type}", body_style))
    story.append(Paragraph(f"<b>Unit system:</b> {units}", body_style))
    story.append(Spacer(1, 4*mm))

    # Inputs
    story.append(Paragraph("Inputs", section_style))
    input_rows = [["Parameter", "Value"]]
    for k, v in inputs.items():
        if isinstance(v, float):
            input_rows.append([str(k), f"{v:.4g}"])
        else:
            input_rows.append([str(k), str(v)])
    t = Table(input_rows, colWidths=[6*cm, 8*cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), DARK_NAVY),
        ("TEXTCOLOR",  (0, 0), (-1, 0), white),
        ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",   (0, 0), (-1, -1), 9),
        ("GRID",       (0, 0), (-1, -1), 0.25, grey),
        ("ALIGN",      (0, 0), (-1, -1), "LEFT"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [white, HexColor("#F4F4F4")]),
    ]))
    story.append(t)
    story.append(Spacer(1, 4*mm))

    # Outputs text
    if outputs_text:
        story.append(Paragraph("Key Results", section_style))
        for line in outputs_text:
            story.append(Paragraph(line, body_style))
        story.append(Spacer(1, 4*mm))

    # Tables (one per dataframe)
    if tables:
        for tbl_title, df in tables:
            story.append(Paragraph(tbl_title, section_style))
            # Convert df to list of lists (header + rows)
            cols = [str(c) for c in df.columns]
            data = [cols]
            for _, row in df.iterrows():
                data.append([f"{v:.4g}" if isinstance(v, (int, float))
                              else str(v) for v in row])
            # Limit table size to first 25 rows for PDF
            if len(data) > 26:
                data = data[:26] + [["...", "...", "...", "...", "...", "..."][:len(cols)]]
            tbl = Table(data, repeatRows=1)
            tbl.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), DARK_NAVY),
                ("TEXTCOLOR",  (0, 0), (-1, 0), white),
                ("FONTSIZE",   (0, 0), (-1, -1), 8),
                ("GRID",       (0, 0), (-1, -1), 0.25, grey),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [white, HexColor("#F4F4F4")]),
            ]))
            story.append(tbl)
            story.append(Spacer(1, 4*mm))

    # Closing
    if notes:
        story.append(Paragraph("Notes", section_style))
        story.append(Paragraph(notes, body_style))

    story.append(Spacer(1, 10*mm))
    story.append(Paragraph(
        "<i>This is an early-phase tool. Results are for screening and "
        "preliminary engineering only. Validate against laboratory PVT "
        "measurements and rigorous flash software before use in field design. "
        "MIT License. © M. Hamdani.</i>",
        body_style))

    doc.build(story)
    pdf_bytes = buf.getvalue()
    buf.close()
    return pdf_bytes
